// Conversation Group orchestration: group.ts's group-agnostic RFC 9420
// engine (the SAME one self-group.ts uses) + mls-ds/client-transport.ts
// (the Conversation Group DS's HTTP transport), for the third-party group
// chat path PLAN_biset-mls-ds.md/PLAN-mimi.md describe. Mirrors
// self-group.ts's shape but is simpler in the ways that follow from having
// no single-owner identity:
//
//   - No identity-derived groupId (self-group.ts's selfGroupIdHex) -- a
//     Conversation Group has no stable "owner" to key one off, so groupId
//     is random (randomConversationGroupId).
//   - No roster-projection reflection (installCurrentRosterProjection) --
//     that machinery is Vault Coordinator's Self Group concept. A
//     Conversation Group's membership changes are reflected into Vault via
//     PLAN-mimi.md §4's DeltaChat-style control messages instead, a
//     different module's job (not this one's).
//
// **Identity-blind DS revision**: every DS-facing operation here signs and
// submits with a `GroupLocalId` (conversation-mls-ds.ts's own note -- a
// fresh, single-group, throwaway Ed25519 keypair, generated by
// `randomGroupLocalKeypair` below), never this device's real MLS/DID
// credential. The MLS layer itself (KeyPackage/LeafNode/Welcome/commit) is
// completely unchanged -- members still recognize each other by their real,
// DID-bound `MlsDeviceCredentialV2` inside the E2E-encrypted group; only
// the DS must never see it. There is no more `joinConversationGroupExternally`
// -- GroupInfo (which would have to expose that same DID-bound credential
// in the clear for an external joiner to validate it) is gone; joining is
// Welcome-only now, via `addMembersToConversationGroup`, always initiated
// by an existing member.
//
// Application-message send/receive (sendConversationApplicationMessage,
// receiveConversationEntry) are the operations Self Group's own
// orchestration has no equivalent of (PLAN-mimi.md's finding) -- Self Group
// never routes application data through its DS.
import { ed25519 } from '@noble/curves/ed25519.js'
import {
  addMembers,
  confirmCommit,
  createMlsGroup,
  encryptApplication,
  epochOf,
  memberList,
  ownMlsDeviceCredential,
  processIncoming,
  removeMembers,
  type OwnKeyPackage,
} from './group.ts'
import type { ClientState, KeyPackage } from './vendor/index.ts'
import { bytesToHex, hexToBytes } from '../protocol/canonical.ts'
import { mlsEpoch } from '../protocol/ids.ts'
import {
  conversationCommitSubmitSigningBytes,
  conversationGroupCreateSigningBytes,
  conversationMessageSubmitSigningBytes,
} from '../protocol/conversation-mls-ds-signing.ts'
import type {
  ConversationCommitSubmitV1,
  ConversationGroupCreateV1,
  ConversationMessageSubmitV1,
  GroupLocalId,
} from '../protocol/conversation-mls-ds.ts'
import type { ConversationMlsDeliveryTransport } from '../mls-ds/client-transport.ts'

export type ConversationGroupSigner = (bytes: Uint8Array) => Uint8Array | Promise<Uint8Array>

/** Random 32-byte hex groupId -- unlike Self Group, there is no stable
 * identity to derive a deterministic id from (multiple members, no single
 * owner). Knowing groupId identifies which group to talk to; it is no
 * longer (as of the identity-blind revision) sufficient on its own to join
 * one -- see this file's header. */
export function randomConversationGroupId(): string {
  return bytesToHex(crypto.getRandomValues(new Uint8Array(32)))
}

export interface GroupLocalKeypair { privateKey: Uint8Array; id: GroupLocalId }

/** A fresh, single-group, throwaway Ed25519 keypair -- generate ONE of
 * these per group, per device (never reuse across groups; reuse is exactly
 * what would let the DS correlate a member across groups, the whole
 * property this identifier model exists to deny it). The public key IS the
 * id: `mls-ds/authorizer.ts` verifies a request's signature directly
 * against `hexToBytes(id)`, no registry or resolution involved. */
export function randomGroupLocalKeypair(): GroupLocalKeypair {
  const privateKey = ed25519.utils.randomSecretKey()
  return { privateKey, id: bytesToHex(ed25519.getPublicKey(privateKey)) }
}

/** Creates a new Conversation Group. `groupId` should come from
 * `randomConversationGroupId` -- this function does not generate one
 * itself, so a caller can log/share it before the group actually exists on
 * the DS. Also generates the creator's own group-local keypair for this
 * group and self-signs `group-create` with it -- `store.ts`'s `createGroup`
 * has no prior roster to check membership against, so nothing beyond the
 * signature itself is needed, and the DS never learns who the creator
 * really is (not even them being the exception -- there is no exception). */
export async function createConversationGroup(
  transport: ConversationMlsDeliveryTransport,
  groupId: string,
  kp: OwnKeyPackage,
  now: () => Date = () => new Date(),
): Promise<{ state: ClientState; ownGroupLocal: GroupLocalKeypair }> {
  const ownGroupLocal = randomGroupLocalKeypair()
  const state = await createMlsGroup(hexToBytes(groupId), kp)
  const creation: Omit<ConversationGroupCreateV1, 'signature'> = { version: 1, groupId, creatorId: ownGroupLocal.id, createdAt: now().toISOString() }
  await transport.createGroup({ ...creation, signature: ed25519.sign(conversationGroupCreateSigningBytes(creation), ownGroupLocal.privateKey) })
  return { state, ownGroupLocal }
}

/** Encrypts `plaintext` (a MimiContent CBOR encoding, mls/mimi-content.ts --
 * this function has no opinion on what's inside) as an MLS application
 * message and logs it with the DS. No push fan-out any more (mls-ds's
 * DIDComm binding was deleted, see conversation-mls-ds.ts's header) --
 * every recipient (including this device's own other sessions) learns of
 * it by pulling (conversation-group-sync.ts). Returns the advanced ratchet
 * state; the caller is responsible for persisting it. */
export async function sendConversationApplicationMessage(
  state: ClientState,
  transport: ConversationMlsDeliveryTransport,
  groupId: string,
  senderId: GroupLocalId,
  plaintext: Uint8Array,
  sign: ConversationGroupSigner,
  now: () => Date = () => new Date(),
): Promise<ClientState> {
  const { state: nextState, wire } = await encryptApplication(state, plaintext)
  const submission: Omit<ConversationMessageSubmitV1, 'signature'> = {
    version: 1, groupId, senderId, epoch: mlsEpoch(epochOf(state)), privateMessage: wire, submittedAt: now().toISOString(),
  }
  const outcome = await transport.submitMessage({ ...submission, signature: await sign(conversationMessageSubmitSigningBytes(submission)) })
  if (!outcome.ok) throw new Error(`sendConversationApplicationMessage: rejected (${outcome.reason})`)
  return nextState
}

export interface NewConversationMember {
  keyPackage: KeyPackage
  /** The new member's own group-local id for this group, obtained via the
   * peer-to-peer join exchange (conversation-group-invite.ts's
   * `CONVERSATION_GROUP_JOIN_READY`) -- not derivable from the KeyPackage
   * itself, which carries only the new member's real, DID-bound MLS
   * credential (deliberately never DS-facing). */
  groupLocalId: GroupLocalId
}

/** Advances the group by a commit that adds `members` as new members (an
 * inviter's half of getting someone into the group -- taking their
 * KeyPackage via `transport.takeKeyPackage` first is the caller's job, same
 * split self-group.ts keeps between MLS state changes and DS I/O). The one
 * way into a Conversation Group now -- there is no external-join path any
 * more (this file's header). */
export async function addMembersToConversationGroup(
  state: ClientState,
  transport: ConversationMlsDeliveryTransport,
  groupId: string,
  senderId: GroupLocalId,
  members: NewConversationMember[],
  sign: ConversationGroupSigner,
  now: () => Date = () => new Date(),
): Promise<ClientState> {
  const result = await addMembers(state, members.map(m => m.keyPackage))
  const submission: Omit<ConversationCommitSubmitV1, 'signature'> = {
    version: 1,
    groupId,
    senderId,
    epoch: mlsEpoch(epochOf(state)),
    commit: result.commit,
    addedIds: members.map(m => m.groupLocalId),
    ...(result.welcome ? { welcome: result.welcome } : {}),
    submittedAt: now().toISOString(),
  }
  const outcome = await transport.submitCommit({ ...submission, signature: await sign(conversationCommitSubmitSigningBytes(submission)) })
  if (!outcome.ok) throw new Error(`addMembersToConversationGroup: commit rejected (${outcome.reason})`)
  confirmCommit(result)
  return result.state
}

export interface RemovedConversationMember {
  /** The member's real MLS leaf kid (`did#fragment`) -- what `removeMembers`
   * (group.ts) actually removes from the ratchet tree. */
  mlsKid: string
  /** The same member's group-local id for THIS group -- what gets dropped
   * from the DS's roster. Only known to whoever added them, or learned some
   * other way (conversation-group-store.ts's own scoped-down limitation,
   * PLAN_biset-mls-ds.md §11) -- there is no way to derive it from `mlsKid`
   * or from `state`. */
  groupLocalId: GroupLocalId
}

/** Advances the group by a commit that removes `removed` -- unlike Self
 * Group's `removeDeviceFromSelfGroup` (which revokes another device of the
 * SAME identity as the committer), a Conversation Group has no notion of
 * "this identity's devices": `removed` may name devices of any member,
 * across any number of distinct identities, in one commit. RFC 9420
 * forbids a commit that removes its own committer (group.ts's own note on
 * `removeMembers`), so `removed` must not include this device's own MLS
 * leaf (`ownMlsDeviceCredential(state)`) -- there is no self-removal
 * wrapper here yet, same as self-group.ts (its own `leaveSelfGroup`
 * referenced in group.ts's comments does not actually exist either;
 * `proposeSelfRemoval` + `transport.submitSelfRemove` are available but
 * unwrapped, for either group kind). */
export async function removeMembersFromConversationGroup(
  state: ClientState,
  transport: ConversationMlsDeliveryTransport,
  groupId: string,
  senderId: GroupLocalId,
  removed: RemovedConversationMember[],
  sign: ConversationGroupSigner,
  now: () => Date = () => new Date(),
): Promise<ClientState> {
  const ownKid = ownMlsDeviceCredential(state).deviceKid
  if (removed.some(r => r.mlsKid === ownKid)) throw new TypeError('removeMembersFromConversationGroup: cannot remove the committing device itself')
  const result = await removeMembers(state, removed.map(r => r.mlsKid))
  const submission: Omit<ConversationCommitSubmitV1, 'signature'> = {
    version: 1,
    groupId,
    senderId,
    epoch: mlsEpoch(epochOf(state)),
    commit: result.commit,
    removedIds: removed.map(r => r.groupLocalId),
    submittedAt: now().toISOString(),
  }
  const outcome = await transport.submitCommit({ ...submission, signature: await sign(conversationCommitSubmitSigningBytes(submission)) })
  if (!outcome.ok) throw new Error(`removeMembersFromConversationGroup: commit rejected (${outcome.reason})`)
  confirmCommit(result)
  return result.state
}

export interface ConversationIncomingEntry {
  state: ClientState
  /** Set only when the entry was an application message -- a commit/
   * proposal advances `state` with no plaintext to hand back. */
  plaintext?: Uint8Array
  /** The kid MLS itself authenticated as the sender -- set alongside
   * `plaintext` whenever `processIncoming` could resolve the sending leaf's
   * credential (group.ts's `memberAt`). A Vault projection MUST attribute a
   * message to this, never to anything self-reported inside the plaintext
   * (group.ts's own `processIncoming` doc comment on why). This is the
   * real, DID-bound MLS kid -- unrelated to, and never derivable from, the
   * sender's DS-facing `GroupLocalId`. */
  sender?: string
}

/** Applies one deliveries-pull entry -- a commit/proposal advances group
 * state with no plaintext; an application message decrypts to `plaintext`
 * (a MimiContent CBOR encoding, mls/mimi-content.ts's job to decode, not
 * this function's). A `'welcome'`-kind entry is NOT handled here -- its
 * wireformat is `mls_welcome`, which `processIncoming` rejects; a joiner
 * consumes it once via `joinMlsGroup` (group.ts) as part of the
 * conversation-group-invite.ts bootstrap flow, not through this
 * steady-state catch-up path. */
export async function receiveConversationEntry(state: ClientState, payload: Uint8Array): Promise<ConversationIncomingEntry> {
  const result = await processIncoming(state, payload)
  return result.kind === 'message' ? { state: result.state, plaintext: result.message, ...(result.sender ? { sender: result.sender.kid } : {}) } : { state: result.state }
}
